title: Adam Bruce
logo: /Job_Materials/headshot.PNG
description: Graduate and Undergraduate Data Science Project Portfolio. Click "View on GitHub" to access project folders with code documents and relevant materials.
show_downloads: true
theme: jekyll-theme-minimal
