title: Adam Bruce
logo: /images/NewHeadshot.PNG
description: Click "View on GitHub" to access project folders with code documents and relevant materials.
show_downloads: true
theme: jekyll-theme-minimal
