title: Adam Bruce
logo: /images/NewHeadshot.PNG
description: Click "View on GitHub" to access project repository with code documents and relevant materials.
show_downloads: false
theme: jekyll-theme-minimal
