title: Adam Bruce
logo: /images/NewHeadshot.PNG
description: Click "View the Project on GitHub" to access the project repository with code documents and relevant materials.
show_downloads: false
theme: jekyll-theme-minimal
