title: Adam Bruce
logo: ~/adam.bruce/Desktop/Job_Materials/headshot.png
description: Graduate and Undergraduate Data Science Project Portfolio. Click "View on GitHub" to access project folders with code documents and relevant materials.
show_downloads: true
theme: jekyll-theme-minimal
